[tool.poetry]
name = "alto2txt2fixture"
version = "0.1.0"
description = ""
authors = ["Kalle Westerling <kalle.westerling@bl.uk>"]

[tool.poetry.dependencies]
python = "^3.9"
tqdm = "^4.65.0"
pandas = "^2.0.2"
colorama = "^0.4.6"
numpy = "^1.24.3"
pytz = "^2022.7.1"
rich = "^12.6.0"
wget = "^3.2"

[tool.poetry.dev-dependencies]
mkdocs = "^1.4.3"
mkdocs-material = "^8.5.11"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"

[tool.poetry.scripts]
run = "run:run"